### PR TITLE
fix(web): Horizontal Scrolling issue on the website

### LINKED ISSUE #437: Horizontal Scrolling Issue on the Website
Description: I have resolved the issue with the footer where the website name was cut off or overlapping with other elements. However, I've identified a new problem with horizontal scrolling on the website.

To Reproduce:

1. Open the website.

2. Observe the horizontal scrolling across different screen sizes.

Expected Behavior: The website should not have horizontal scrolling and should fit within the viewport without extending beyond it.

### PR DESCRIPTION
**Pull request by Samaresh-Das**
## Description

The website had a horizontal scroll bar when changing to different screen sizes. The tailwind breakpoints were not used properly in my opinion. So I added some more breakpoints so it becomes more responsive as some cards in the page are pushing the beyond the View port. There were two options, either tweak the width of the cards or change the grid layout. Changing the width of the cards making elements look bad in other sections of the page and is overall not a good idea as card is a reusable component. So I changed the parent container div layout. On desktop screen it will be 3, on tablet size it will be 2. I didn't touched the mobile responsive design.

Video- 

https://github.com/user-attachments/assets/47d9e64a-634f-4d85-933c-c0ba0def965f

Fixes #437 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
enhancement

___

### **Description**
- Enhanced the grid layout across multiple components to address horizontal scrolling issues and improve responsiveness.
- Adjusted grid columns for different screen sizes, ensuring better layout on desktop, tablet, and mobile devices.
- Added conditional rendering in `LifeEasySection` to optimize display based on screen size.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Update grid layout for responsive design</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/src/components/colabEasy/index.tsx

<li>Modified grid layout to improve responsiveness.<br> <li> Adjusted grid columns for different screen sizes.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/440/files#diff-bb0ee8872c7642b1cf4cfcf2c20485d8989b412e6144542efa7b2ff84d357196">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Enhance grid layout for better responsiveness</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/src/components/lifeEasySection/index.tsx

<li>Changed grid layout to improve responsiveness.<br> <li> Added conditional rendering for different screen sizes.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/440/files#diff-af73fd1857014d1a2e0476717c478d52b7e8ad3692a94f839d73cd8912a21453">+26/-2</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Improve grid layout for responsive design</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/src/components/secretSection/index.tsx

<li>Updated grid layout for improved responsiveness.<br> <li> Adjusted grid columns for various screen sizes.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/440/files#diff-e42a662789f9e2bea79e3dcf930ced9a457453fc06e433151aa446b65c78ba8b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by rajdip-b** [comment]
@kriptonian1 could you review this and get it merged?

**Review by kriptonian1 — APPROVED** [review]
LGTM

**Comment by m7md-Y-3mra** [comment]
I wanted to bring to your attention a problem I’ve encountered related to the recent changes merged in this PR. There is a horizontal scrolling issue when the screen width is between 762px and 852px.

**Pull request merged**
