### PR TITLE
chore: Clearing email field after waitlisting the user email

### PR DESCRIPTION
**Pull request by bansal-harsh-2504**
## Description
Now if the user email gets waitlisted then the email field will be cleared for better user experience.

Related to #474 

## Mentions
@rajdip-b 

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings

### Documentation Update
- [ ] No documentation changes are required.

___

### **PR Type**
enhancement

___

### **Description**
- Fixed a typo in the error message displayed when the email field is empty.
- Enhanced user experience by clearing the email input field after the email is successfully waitlisted.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Improve user experience by clearing email field post-waitlisting</code></dd></summary>
<hr>

apps/web/src/components/hero/index.tsx

<li>Fixed a typo in the error message for empty email input.<br> <li> Added functionality to clear the email field after successful <br>waitlisting.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/481/files#diff-7613ce5c9e898c20a2427ba5bf13810f61bb0a532139896e00a54cd0285ad40c">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by rajdip-b — APPROVED** [review]
LGTM

**Comment by rajdip-b** [comment]
@kriptonian1 can you review and merge this? Just make sure the original issue doesn't get closed

**Comment by bansal-harsh-2504** [comment]
@kriptonian1 @rajdip-b Can you please add hacktoberfest label before merging?

**Comment by rajdip-b** [comment]
for sure

**Pull request merged**
