### PR TITLE
feat: husky configured

### LINKED ISSUE #1: [FEATURE REQUEST]: Add Husky
**Is your feature request related to a problem? Please describe.**
Add Husky to the project to make pre-commit validations

**Describe the solution you'd like**
The pre-commit should do the following:
- lint the code for errors
- fix the errors (if fixable)
- run prettier fix on the entire project

### PR DESCRIPTION
**Pull request by Abbhiishek**
## Type
Enhancement

___

## Description
- Introduced Husky into the development workflow.
- Configured Husky to run `lint:fix` script before every commit.
- Updated `lint:fix` script in `package.json` to exclude `sdk-rust` project from the linting process.
- Added Husky to devDependencies in `package.json`.
- Added a `prepare` script in `package.json` for Husky installation.
- Updated the `pnpm-lock.yaml` file to include Husky and removed the `js:library` dependency.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>pre-commit&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        .husky/pre-commit<br><br>

**Added a pre-commit hook script to run the `lint:fix` <br>command.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/32/files#diff-d2bc4bbf14eadc292d84e0ef5f7a93115c23557f533809fc80b896934291529d"> +4/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>package.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        package.json<br><br>

**Added Husky to devDependencies, updated the `lint:fix` <br>script to exclude `sdk-rust` project from linting process, <br>and added a `prepare` script for Husky installation.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/32/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519"> +4/-3</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pnpm-lock.yaml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        pnpm-lock.yaml<br><br>

**Updated the lock file to include Husky and removed the <br>`js:library` dependency.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/32/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb"> +9/-9</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

## Description

This PR introduces **`Husky`** into our development workflow.

**Changes**:

1. Added Husky to `devDependencies` in `package.json`
2. Configured Husky to run `lint:fix` script before `every commit`
3. Updated `lint:fix` script to exclude `sdk-rust` project from linting process

Fixes #1 

## Dependencies

_Mention any dependencies/packages used_

-  [Husky](https://www.npmjs.com/package/husky)

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

@rajdip-b 

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

Ps. Please review the changes and provide your feedback.

### CODE REVIEW

**Review by rajdip-b — APPROVED** [review]
Looks nice!

**Comment by Abbhiishek** [comment]
Thanks @rajdip-b  for merging the pr.

**Comment by rajdip-b** [comment]
We're really happy that you are contributing actively!

**Pull request merged**
