### PR TITLE
chore(platoform): Swapped all legacy API calls with `@keyshade/api-client`

### PR DESCRIPTION
**Pull request by poswalsameer**
## Description
This PR changes all the old API calls made in the platform to new by utilizing the `@keyshade/api-client` package.

## Dependencies
No dependencies.

## Mentions
@rajdip-b 

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
enhancement

___

### **Description**
- Refactored API calls in the secret page to use `SecretController` from `@keyshade/api-client`, replacing legacy methods.
- Updated the project layout to use `ProjectController` from `@keyshade/api-client`, enhancing the data fetching process.
- Improved error handling and loading state management in both components.
- Modified data structure references to align with the new API schema.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>page.tsx</strong><dd><code>Refactor secret page to use new API client</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/platform/src/app/(main)/project/[project]/@secret/page.tsx

<li>Replaced legacy API calls with <code>SecretController</code> from <br><code>@keyshade/api-client</code>.<br> <li> Updated data fetching logic to use async/await.<br> <li> Modified data structure references to align with new API.<br> <li> Improved error handling and loading state management.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/584/files#diff-bcf503c2f7b83925679fb899afa7c99d686d5be5097449bea9b6ba5d794e7467">+33/-19</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>layout.tsx</strong><dd><code>Refactor project layout to use new API client</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/platform/src/app/(main)/project/[project]/layout.tsx

<li>Replaced legacy API calls with <code>ProjectController</code> from <br><code>@keyshade/api-client</code>.<br> <li> Updated data fetching logic to use async/await.<br> <li> Improved error handling.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/584/files#diff-c4040a6a4dfc70b1922425378ad1337f4fe81815edb696ddff654068eeadba84">+23/-8</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by rajdip-b — COMMENTED** [review]
can you delete the existing controllers in `/lib/api-functions`?

**Comment by poswalsameer** [comment]
> can you delete the existing controllers in `/lib/api-functions`?

deleted two files inside the `lib` folder, `controller-instance.ts` is getting utilised in the auth and `utils.ts` is related to tailwind, so kept these two files as it is.

**Comment by poswalsameer** [comment]
> We also have auth functions in API Client. Could you please try to refactor that aswell? Do lmk if you run into any issues.

Sure, will do it.

**Comment by rajdip-b** [comment]
@poswalsameer could you please wrap this up? it would be very helpful to us

**Comment by poswalsameer** [comment]
> @poswalsameer could you please wrap this up? it would be very helpful to us

Hi, I am done with this. Removed all the legacy code I found in the codebase.

**Comment by rajdip-b** [comment]
I think the auth functions are still missing as per our previous convo

**Comment by poswalsameer** [comment]
> I think the auth functions are still missing as per our previous convo

You talking about this file inside the `api-client`, because I didn't find any other file related to auth.
Screenshot 2024-12-17 163755

**Comment by rajdip-b** [comment]
> > can you delete the existing controllers in `/lib/api-functions`?
> 
> deleted two files inside the `lib` folder, `controller-instance.ts` is getting utilised in the auth and `utils.ts` is related to tailwind, so kept these two files as it is.

Im talking about this

**Pull request merged**
