### PR TITLE
chore: Update controller invocation in environment commands

### LINKED ISSUE #443: CLI: Update controller invocation in `environment` commands
## Description

https://github.com/keyshade-xyz/keyshade/blob/ed38d2227020a08972658771d211fe2316f41367/apps/cli/src/commands/environment/list.environment.ts#L35-L40
All the files of `environment` command are using this pattern to initiate the controller. This has been changed in the latest push.  

## Solution

Make all the environment commands use the newer way to call the controller: https://github.com/keyshade-xyz/keyshade/blob/ed38d2227020a08972658771d211fe2316f41367/apps/cli/src/commands/workspace/create.workspace.ts#L37-L44

### PR DESCRIPTION
**Pull request by bansal-harsh-2504**
## Description

Updated controller invocation in environment commands in 
keyshade/apps/cli/src/commands/environment/list.environment.ts

Fixes #443 

## Mentions

@rajdip-b 

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] There are no UI/UX issues

### Documentation Update
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
enhancement

___

### **Description**
- Refactored the environment fetching logic to use a centralized `ControllerInstance` instead of directly instantiating `EnvironmentController`.
- Simplified headers management by utilizing `this.headers` within the command.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>list.environment.ts</strong><dd><code>Refactor environment fetching to use ControllerInstance</code>&nbsp; &nbsp; </dd></summary>
<hr>

apps/cli/src/commands/environment/list.environment.ts

<li>Replaced <code>EnvironmentController</code> import with <code>ControllerInstance</code>.<br> <li> Updated method to use <code>ControllerInstance</code> for fetching environments.<br> <li> Removed manual headers setup, using <code>this.headers</code> instead.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/477/files#diff-98e45816c7ac3ca77c1edecd3562146bfd4c9a30ab6f818de69daa6e0b6de5fe">+7/-14</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by rajdip-b** [comment]
You would need to make these changes across all of the environment commands in that folder!

**Comment by bansal-harsh-2504** [comment]
@rajdip-b I apologize for the oversight in my initial submission where I updated only one file. I have now corrected this and applied the necessary changes across all the environment commands. Please review the updated files at your convenience.

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Instead of using `../../util/controller-instance`, use `@/util/controller-instance`

**Comment by rajdip-b** [comment]
> @rajdip-b I apologize for the oversight in my initial submission where I updated only one file. I have now corrected this and applied the necessary changes across all the environment commands. Please review the updated files at your convenience.

All of the changes look good, just fix the import and we should be good to go :)

**Comment by bansal-harsh-2504** [comment]
@rajdip-b  Can you please attach hacktoberfest label before merging?

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
