### PR TITLE
chore: Added docker build and run commands to` package.json`

### LINKED ISSUE #257: Add docker build and run commands to `package.json`
## Description

Adding the docker commands to `package.json` will help developers to better test their builds. 

## Solution

Add the following scripts to the root `package.json`:

- `docker:build:api`
- `docker:run:api`
- `docker:build:web`
- `docker:run:web`
- `docker:build:platform`
- `docker:run:platform`

### PR DESCRIPTION
**Pull request by vr-varad**
## Description

Added docker build and run commands._ <br />

Fixes #257 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Comment by vr-varad** [comment]
@rajdip-b done.

**Review by rajdip-b — CHANGES_REQUESTED** [review]
The commands look good. Can you additionally add `--env-file .env` to the run commands?

**Comment by vr-varad** [comment]
@rajdip-b  made the suggested changes

**Comment by rajdip-b** [comment]
Cool! I'll test them out.

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Hey man, the PR looks good and works fine. I just forgot to mention two other flags:

- `--name <container name>`
- `--rm`

Once you have added these, we are good to merge!

**Comment by vr-varad** [comment]
@rajdip-b done

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
