### PR TITLE
feat: added the auto assign workflow yaml file

### LINKED ISSUE #52: Auto assign workflow
Would like to have a possible way to do the following:

- Contributors can type `/attempt` in any issue comments
- A CI will assign the issue to the commentor if it has not been assigned already, else, will display a message that the action needs the interference of the maintainers

The suggested features should be created in a GitHub Actions file. Preferably, name it `auto-assign.yaml`

It would be a huge plus if you can also update the `CONTRIBUTION.md` with the steps accordingly!

### PR DESCRIPTION
**Pull request by lakshay-saini-au8**
## Type
Enhancement

___

## Description
This PR introduces a new GitHub Actions workflow that automates the assignment of issues. The key changes include:
- A new workflow file `.github/workflows/auto-assign.yaml` has been added.
- The workflow triggers on the creation of an issue comment.
- If a user comments "/attempt" on an unassigned issue, the issue gets assigned to them.
- If the issue is already assigned, a comment is added to inform the user.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>auto-assign.yaml&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        .github/workflows/auto-assign.yaml<br><br>

**This file is a new addition to the project. It defines a <br>GitHub Actions workflow that automatically assigns an issue <br>to a user when they comment "/attempt", provided the issue <br>is not already assigned. The workflow runs on the creation <br>of an issue comment. If the issue is already assigned, a <br>comment is added to inform the user.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/72/files#diff-e0a21e719f493a2590d8bc4d9e368899ca299974fa677f5af975e9a2ddfdb0dc"> +34/-0</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

## Description

Auto-assign the issue if it is not assigned to anyone if they comment "/attempt"

Fixes #52 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b 

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ x My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Looks good, can you also update the CONTRIBUTIONS.md?

**Comment by rajdip-b** [comment]
Hey @lakshay-saini-au8, also just for my understanding. When the workflow file registers a comment in the issue, what profile does it show? Like, github-bot or actions-bot or something. I need to be clear on this before we can merge it

**Comment by lakshay-saini-au8** [comment]
> Hey @lakshay-saini-au8, also just for my understanding. When the workflow file registers a comment in the issue, what profile does it show? Like, github-bot or actions-bot or something. I need to be clear on this before we can merge it

For this, it will be like github-actions[bot]

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
