### PR TITLE
feat(api): Add env, secret, and variable count in project

### LINKED ISSUE #308: API: Send Total numbers of Environments, Variables, and Secrets
## Description
The frontend needs the total number of Environments, Variables, and Secrets for aesthetic purposes

## Scope of Work

- Send the total number of env, var, and secrets of each project of workspace when calling the API for `Get all projects by workspace ID` which have the url of [`/api/project/all/:workspace_id`
](https://github.com/keyshade-xyz/keyshade/blob/b272df3210e7338be0722d6711cf110998500cb7/apps/api/src/project/controller/project.controller.ts#L101-L121)

## Function of the operation
https://github.com/keyshade-xyz/keyshade/blob/b272df3210e7338be0722d6711cf110998500cb7/apps/api/src/project/service/project.service.ts#L625-L672

### PR DESCRIPTION
**Pull request by unamdev0**
## Description

Sending total Count of env,variable and secrets when fetching project data for a workspace

Fixes #308 

## Screenshots of response
Screenshot 2024-09-14 at 12 27 27 PM

## Further improvement

- [] Need to update postman
Sample response
 ```{
    "items": [
        {
            "id": "c6d92085-0e85-4986-a1d3-7923583efa22",
            "name": "Project 1",
            "slug": "project-1-oa2j9",
            "description": "Dummy project 1",
            "createdAt": "2024-09-13T15:45:42.014Z",
            "updatedAt": "2024-09-13T15:45:42.014Z",
            "storePrivateKey": true,
            "isDisabled": false,
            "accessLevel": "PRIVATE",
            "isForked": false,
            "lastUpdatedById": "cm0v65bm00000130sigtvry7y",
            "workspaceId": "3b41add3-4e14-4866-a6e8-0669d1d7b08b",
            "forkedFromId": null,
            "totalEnvironmentsOfProject": 3,
            "totalVariablesOfProject": 1,
            "totalSecretsOfProject": 1
        },
        {
            "id": "45dae533-8556-4621-b841-43502fe85752",
            "name": "Project 2",
            "slug": "project-2-o9rl4",
            "description": "Dummy project 1",
            "createdAt": "2024-09-13T16:25:40.877Z",
            "updatedAt": "2024-09-13T16:25:40.877Z",
            "storePrivateKey": true,
            "isDisabled": false,
            "accessLevel": "PRIVATE",
            "isForked": false,
            "lastUpdatedById": "cm0v65bm00000130sigtvry7y",
            "workspaceId": "3b41add3-4e14-4866-a6e8-0669d1d7b08b",
            "forkedFromId": null,
            "totalEnvironmentsOfProject": 3,
            "totalVariablesOfProject": 0,
            "totalSecretsOfProject": 0
        },
        {
            "id": "5392bcb8-dcd7-41d3-9c78-1adfa0818f1b",
            "name": "Project 3",
            "slug": "project-3-b8i47",
            "description": "Dummy project 1",
            "createdAt": "2024-09-13T16:27:25.038Z",
            "updatedAt": "2024-09-13T16:27:25.038Z",
            "storePrivateKey": true,
            "isDisabled": false,
            "accessLevel": "PRIVATE",
            "isForked": false,
            "lastUpdatedById": "cm0v65bm00000130sigtvry7y",
            "workspaceId": "3b41add3-4e14-4866-a6e8-0669d1d7b08b",
            "forkedFromId": null,
            "totalEnvironmentsOfProject": 1,
            "totalVariablesOfProject": 0,
            "totalSecretsOfProject": 0
        }
    ],
    "metadata": {
        "page": 0,
        "perPage": 10,
        "pageCount": 1,
        "totalCount": 3,
        "links": {
            "self": "/project/all/my-first-workspace-rbqs2?page=0&limit=10&sort=name&order=asc&search=project 1",
            "first": "/project/all/my-first-workspace-rbqs2?page=0&limit=10&sort=name&order=asc&search=project 1",
            "previous": null,
            "next": null,
            "last": "/project/all/my-first-workspace-rbqs2?page=0&limit=10&sort=name&order=asc&search=project 1"
        }
    }
}
```

___

### **PR Type**
enhancement, tests

___

### **Description**
- Added helper functions for fetching environments, variables, and secrets with pagination, sorting, and search capabilities.
- Refactored environment, secret, and variable services to utilize new helper functions, simplifying logic and improving maintainability.
- Enhanced project service to include total counts of environments, variables, and secrets.
- Expanded project controller tests to cover fetching of environments, variables, and secrets.
- Made minor code cleanups and formatting improvements in workspace-related files.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>environment.ts</strong><dd><code>Add helper for fetching project environments with pagination</code></dd></summary>
<hr>

apps/api/src/common/environment.ts

<li>Added a new interface <code>getEnvironmentsOfProjectHelperInput</code>.<br> <li> Implemented <code>getEnvironmentsOfProjectHelper</code> function for fetching <br>environments.<br> <li> Included pagination, sorting, and search capabilities.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-84956eeff475d75103e8f326f7fe070c5a7f050fef2c9be2c6e44bccb006dc42">+104/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>secret.ts</strong><dd><code>Implement helper for retrieving project secrets</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/common/secret.ts

<li>Introduced <code>getSecretsOfProjectHelper</code> function.<br> <li> Added logic for fetching and decrypting secrets.<br> <li> Implemented pagination and search functionality.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-345fe7aa21c4f70c5831b5ed6a4b07e02d6001de276dd99069a8f88dea4910c9">+213/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>variable.ts</strong><dd><code>Add helper for fetching project variables with pagination</code></dd></summary>
<hr>

apps/api/src/common/variable.ts

<li>Added <code>getVariablesOfProjectHelper</code> function.<br> <li> Implemented logic for fetching variables with pagination.<br> <li> Included search and sorting features.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-9840efb1eb46e994e6d25680edd4657703f6ad241cfee0f8d92d20796d545621">+175/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>environment.service.ts</strong><dd><code>Refactor environment service to use helper function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/environment/service/environment.service.ts

<li>Refactored to use <code>getEnvironmentsOfProjectHelper</code>.<br> <li> Simplified environment fetching logic.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-658d3ecf90efc583248d280885f43ee30a341ca9949c2a48c1312d3ed6f3acbd">+18/-54</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project.service.ts</strong><dd><code>Enhance project service to include environment, variable, and secret </code><br><code>counts</code></dd></summary>
<hr>

apps/api/src/project/service/project.service.ts

<li>Integrated helper functions for fetching environments, variables, and <br>secrets.<br> <li> Enhanced project fetching to include total counts.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-d85f483eff15c28a4b3e5f7a54c9b159c71003f8a95ef7a4be00eb80ec72b2fa">+41/-1</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>secret.service.ts</strong><dd><code>Refactor secret service to utilize helper function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/secret/service/secret.service.ts

<li>Refactored to use <code>getSecretsOfProjectHelper</code>.<br> <li> Removed redundant secret fetching logic.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-dee38177617754972e3d3f727d7f1536566d7a784b7ffdda74aa97d6eec4cbc5">+24/-163</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>variable.service.ts</strong><dd><code>Refactor variable service to use helper function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/variable/service/variable.service.ts

<li>Refactored to use <code>getVariablesOfProjectHelper</code>.<br> <li> Simplified variable fetching logic.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-db1895137a9c036373abefb8c924150d4f2022fd6d4f5271cc6c95c443bf01cf">+22/-129</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>project.e2e.spec.ts</strong><dd><code>Enhance project controller tests for environment and secret fetching</code></dd></summary>
<hr>

apps/api/src/project/project.e2e.spec.ts

<li>Added tests for fetching environments, variables, and secrets.<br> <li> Introduced a new project for testing.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-f1b22baab0b4173d825570c9030ef014582bc75bb67ef2e544f0dd879ff941a2">+101/-7</a>&nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Miscellaneous</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>create.workspace.ts</strong><dd><code>Clean up create workspace DTO</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/workspace/dto/create.workspace/create.workspace.ts

- Removed unused import.
- Minor formatting adjustments.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-c760c1ab4fbc21b71e76046a55e199b8bff73f6924dcab6615a505afc644f924">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>workspace.service.ts</strong><dd><code>Simplify workspace service imports</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/workspace/service/workspace.service.ts

- Removed unnecessary imports.
- Minor code formatting improvements.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/428/files#diff-a92613f23cf2834d52eaedb87c4e8c460d48b6fca8df4ccc968b2a8af19a9c3f">+2/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by rajdip-b — COMMENTED** [review]
Okay, I think you have severely over-engineered the solution. 

1. I see that you are fetching the project at 3 places, when we can have it just at one place
2. I'm not sure why you would need to move out the pagination code to some other block. We won't need that module to be re-usable.

Here's my solution:
- In the function that is responsible for fetching all projects of a workspace, we would need to update the way projects are fetched: 
image
- Once we have fetched all the paginated projects, we want to loop through each of them and then, we need to fetch the total number of environments, secrets and variables associated with this project.
- Declare `totalEnvironments`, `totalSecrets` and `totalVariables` in the loop.
- We do so using this: get a list of all the environments in the project, check the permission of each environment.
- If the user has `READ_ENVIRONMENT`, `READ_VARIABLE` and `READ_SECRET` permissions associated with this environment, we increment the `totalEnvironments` count by 1, and we will be incrementing the count of `totalSecrets` and `totalVariables` by fetching the number of secrets and variables present in the project+env combo.
- We now store the details of the project along with the count details in a list outside of the for loop.
- When the loop ends, we send back the list.

**Comment by rajdip-b** [comment]
P.S. I would highly recommend you to discuss your approach with us over Discord/GitHub before you start implementing it. We don't want you to waste your time building something that won't be suitable to us!

**Comment by unamdev0** [comment]
My first approach was to just calculate total count directly in this function, but since there was this previous [PR](https://github.com/keyshade-xyz/keyshade/pull/311/files) which was almost merged, I tried to replicate this including your suggestion in the [comment](https://github.com/keyshade-xyz/keyshade/pull/311#pullrequestreview-2157088622). And since the same code is being fetched in other services as well, that's why removed the code as to avoid duplication.

If this doesn't need to happen, wouldn't it be easier just to check for user's permission and fetch total count of environments,variables and secret using a query like [this](https://github.com/unamdev0/keyshade/blob/20ad124b48adcf51cc7b6cc8236249aee6b8195b/apps/api/src/common/environment.ts#L157). Please confirm @rajdip-b

**Comment by rajdip-b** [comment]
Yeah, that PR was closed because the suggestions were not implemented. And yes, we could do this but the issue is, down the line we would also be restricting access to environments. So when that happens we would again need to update the code into what i'm suggestion now. To not make the changes over again, I would like you to implement that.

And I doubt that the functionality would be reused since the implementation that i suggested is for a very specific usecase.

**Pull request closed without merging**
