### PR TITLE
feat(web): Added extra check for already waitlisted users and created toast message for them

### LINKED ISSUE #463: WEB: suggesting changes while adding waitlist
# Description 
- [x] [chore] Right now after adding the user to the waitlist there the text field remains the same, instead lets clear the text field. (#481)
- [x] [chore] Perform some validation on the email field as `ff@ff` and other things is allowed which should not be allowed. (#487)
- [x] [chore] Only show toast when the whitelist response is successful. (#490)
- [ ] [feat] Check if user has already whitelisted. (#492)

---
Target file: https://github.com/keyshade-xyz/keyshade/blob/72281e66569b05011a7b79a94ae502eaac0b3a6d/apps/web/src/components/hero/index.tsx

### PR DESCRIPTION
**Pull request by poswalsameer**
## Description
This PR solves the issue by showing an error/warning toast message to already existing users on the waitlist. Before this PR, every user with a single email was getting the success toast message multiple times. Ideally, this should not happen, every user should be able to join the waitlist one time through one email. This PR fixes this problem.

Related to #463 

## Dependencies
No extra package used.

## Screenshots of relevant screens
Screenshot (94)

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Comment by HarshPatel5940** [comment]
Intresting to solve this using local storage. Should work fine for now. Need to look out for a better approach on the longer run.

> Also interestingly, Quite a lot of formatting changes.

**Comment by poswalsameer** [comment]
> Intresting to solve this using local storage. Should work fine for now. Need to look out for a better approach on the longer run.
> 
> > Also interestingly, Quite a lot of formatting changes.

Yes, there can be future improvements on this. Actually, I was not able to find where the data for waitlisted emails is, that's why incorporated local storage here. Regarding the formatting changes, these were automatically made while running the lint check and when committing to GitHub. The only file manually changed by me is the file linked in issue #463.

**Comment by HarshPatel5940** [comment]
> Yes, there can be future improvements on this. Actually, I was not able to find where the data for waitlisted emails is, that's why incorporated local storage here. Regarding the formatting changes, these were automatically made while running the lint check and when committing to GitHub. The only file manually changed by me is the file linked in issue #463.

Okay cool, noted.

**Review by HarshPatel5940 — APPROVED** [review]
The core logical changes to the hero component looks good to me! 👍🏼

**Comment by poswalsameer** [comment]
> The core logical changes to the hero component looks good to me! 👍🏼

Thanks for approving.

**Review by rajdip-b — APPROVED** [review]

**Review by kriptonian1 — CHANGES_REQUESTED** [review]
There are many duplicate files from `cli`, `platform`, and `packages`. You need to only commit the files you worked on.

**Comment by poswalsameer** [comment]
> There are many duplicate files from `cli`, `platform`, and `packages`. You need to only commit the files you worked on.

Hi, those changes took place automatically during linting, neither of them was manually done by me.

**Comment by rajdip-b** [comment]
@kriptonian1 i think its okay to have those changes. the linter did its job and formatted the files as per our standards. imo its a good thing

**Comment by kriptonian1** [comment]
@poswalsameer you can refer this https://www.geeksforgeeks.org/how-to-undo-a-commit-in-git/

**Comment by poswalsameer** [comment]
> @poswalsameer you can refer this https://www.geeksforgeeks.org/how-to-undo-a-commit-in-git/

Thanks for letting me know, actually I did git add . knowingly. I thought you would need the linter changes. No worries, will create another PR for the same.

**Comment by kriptonian1** [comment]
> > @poswalsameer you can refer this https://www.geeksforgeeks.org/how-to-undo-a-commit-in-git/
> 
> Hi, did the said changes, tried committing only the changed file, but the commit failed. It says to remove 2 lines from ./husky/pre-commit. But I don't think so I need to alter that file. I am looking forward for your reply.

Can you drop the screenshot

**Comment by poswalsameer** [comment]
> > > @poswalsameer you can refer this https://www.geeksforgeeks.org/how-to-undo-a-commit-in-git/
> > 
> > 
> > Hi, did the said changes, tried committing only the changed file, but the commit failed. It says to remove 2 lines from ./husky/pre-commit. But I don't think so I need to alter that file. I am looking forward for your reply.
> 
> Can you drop the screenshot

**You can see here I have only staged the file that I have changed:** 
Screenshot (99)

**Here is the error which I am seeing on my terminal:**
Screenshot (100)
Screenshot (101)


I even installed turbo again, but I don't think turbo has anything to do with this.

**Comment by kriptonian1** [comment]
@poswalsameer have you installed `turbo` globally?

**Comment by poswalsameer** [comment]
> @poswalsameer have you installed `turbo` globally?

yes

**Comment by kriptonian1** [comment]
It looks like the issue is with turbo package installation, I am assuming you did the installation with `npm install turbo --global` command, right?

**Comment by kriptonian1** [comment]
I assume the husky issue is happening due to their new version, we are working with version with v9 as far as I can recall but you have v10 I assume. Maybe you can refer to these to resolve this.
- https://github.com/typicode/husky/issues/1480
- https://typicode.github.io/husky/migrate-from-v4.html
- https://javascript.plainenglish.io/migrating-husky-to-v9-33c1f02eb3a9

**Comment by poswalsameer** [comment]
> I assume the husky issue is happening due to their new version, we are working with version with v9 as far as I can recall but you have v10 I assume. Maybe you can refer to these to resolve this.
> 
> * [[docs] Please remove the following lines from your hook scripts typicode/husky#1480](https://github.com/typicode/husky/issues/1480)
> * https://typicode.github.io/husky/migrate-from-v4.html
> * https://javascript.plainenglish.io/migrating-husky-to-v9-33c1f02eb3a9

I will look into it one more time.

**Comment by kriptonian1** [comment]
Let me know if you face any issues, we can get on a call to fix it

**Comment by poswalsameer** [comment]
> Let me know if you face any issues, we can get on a call to fix it



> Let me know if you face any issues, we can get on a call to fix it

Hi, done with the fix, committed only that single file to the branch. Should I create another PR?

**Comment by poswalsameer** [comment]
> Let me know if you face any issues, we can get on a call to fix it

Right now, you can see the changes in this PR, but I think I should create another PR for this. Let me know your thoughts on this!

**Comment by kriptonian1** [comment]
> > Let me know if you face any issues, we can get on a call to fix it
> 
> Right now, you can see the changes in this PR, but I think I should create another PR for this. Let me know your thoughts on this!

I think that will be better idea

**Comment by poswalsameer** [comment]
> > > Let me know if you face any issues, we can get on a call to fix it
> > 
> > 
> > Right now, you can see the changes in this PR, but I think I should create another PR for this. Let me know your thoughts on this!
> 
> I think that will be a better idea. You can close this PR and drop the link of the new PR here.

great, will drop a new PR by EOD.

**Comment by poswalsameer** [comment]
> No extra package used.

I have created a new PR #491. You can review the code, and merge it if everything's fine now. It was a nice experience working on this issue.

**Pull request closed without merging**
