### PR TITLE
chore(api): Change type of id field of models to uuid

### LINKED ISSUE #231: API: Convert all `id` types in `schema.prisma` to be of type UUID v4
## Description

We want to set a standard UUID v4 IDs for our models. Prisma allows us to do this via using DB specific types. Refer to [this](https://github.com/prisma/prisma/issues/2933#issuecomment-770886156) thread to understand how it's done. Ideally, we would want to alter all of our `id` fields across all the models.

### PR DESCRIPTION
**Pull request by Ratnesh2003**
## Description

Modified all the `id` fields inside each model in prisma and changed their types to `uuid` <br />

Fixes #231 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b 

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
enhancement, dependencies

___

### **Description**
- Changed the default value of `id` fields from `cuid()` to `uuid()` in multiple Prisma models to ensure consistency and uniqueness.
- Updated dependencies in `pnpm-lock.yaml` to reflect the changes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>schema.prisma</strong><dd><code>Change `id` field default value to `uuid()` in Prisma models.</code></dd></summary>
<hr>

apps/api/src/prisma/schema.prisma
<li>Changed the default value of <code>id</code> fields from <code>cuid()</code> to <code>uuid()</code> in <br>multiple models.<br> <li> Updated models include <code>Event</code>, <code>Notification</code>, <code>User</code>, <code>Subscription</code>, <br><code>Integration</code>, <code>Environment</code>, <code>Project</code>, <code>ProjectWorkspaceRoleAssociation</code>, <br><code>WorkspaceRole</code>, <code>WorkspaceMemberRoleAssociation</code>, <code>WorkspaceMember</code>, <br><code>SecretVersion</code>, <code>Secret</code>, <code>VariableVersion</code>, <code>Variable</code>, <code>ApiKey</code>, <code>Otp</code>, <br><code>Workspace</code>, <code>Approval</code>, and <code>ChangeNotificationSocketMap</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/232/files#diff-24191263d57c55d02e0cdf394de15225b628d1da20bd826b1541b59b6b02adb4">+19/-19</a>&nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>pnpm-lock.yaml</strong><dd><code>Update dependencies in `pnpm-lock.yaml`.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pnpm-lock.yaml
- Updated dependencies as part of the changes.

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/232/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb">+10783/-8812</a></td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by rajdip-b — CHANGES_REQUESTED** [review]
You forgot to generate the migration files! Do so using `pnpm db:generate-migrations`

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Also, we would need the uuid to be v4 explicitely. Follow up the thread I dropped in the issue to understand how that works.

**Comment by Ratnesh2003** [comment]
Using this should do the job, right?
```prisma
model Event {
  id      String     @id @db.Uuid @default(dbgenerated("gen_random_uuid()"))
  ...
}
```

**Comment by rajdip-b** [comment]
I think you will need to use `uuid_generate_v1` instead of `gen_random_uuid`. Also, test if it works for you or not!

**Comment by Ratnesh2003** [comment]
Both of the functions `gen_random_uuid()` and `uuid_generate_v4()` generates a V4 UUID string.
https://www.postgresql.org/docs/current/functions-uuid.html#FUNCTIONS-UUID

But to be specific about version, yes I think `uuid_generate_v4()` would be better.

**Comment by rajdip-b** [comment]
Wow! Okay I didn't know that, but yeah, staying version specific would help!

**Pull request closed without merging**
