### PR TITLE
chore(eslint): Fix Lint Rules

### PR DESCRIPTION
**Pull request by HarshPatel5940**
#45 

## Description
- I have updated the default eslint rules, so they behave as expected
```json
"@typescript-eslint/no-unused-vars": "warn",
"@typescript-eslint/no-unused-expressions": "warn"
```
and after this i have updated [@nx/eslint](https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks#options) rules.

## Mentions
@rajdip-b 

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work
- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [x] I have added relevant screenshots in my PR

___

## **Type**
Enhancement

___

## **Description**
This PR enhances the project's linting configuration:
- It updates the ESLint rules to include warnings for unused variables and expressions in TypeScript files.
- It adds dependency checks for package and project JSON files.
- It changes the linting executor to `@nx/linter:eslint` for several apps and packages.
- It updates the lint file patterns to include `.ts`, `package.json`, and `project.json` files for several apps and packages.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>.eslintrc.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        .eslintrc.json<br><br>

**The ESLint configuration file was updated with new rules for <br>TypeScript files and for `{package,project}.json` files. The <br>new rules include warnings for unused variables and <br>expressions in TypeScript, and dependency checks for package <br>and project JSON files.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/50/files#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090f"> +17/-1</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/api-e2e/project.json<br><br>

**The linting executor was changed to `@nx/linter:eslint` and <br>the lint file patterns were updated to include `.ts`, <br>`package.json`, and `project.json` files in the `api-e2e` <br>app.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/50/files#diff-f29ccf22b143aa5523d017091f262be3bd070c5d95436e021d3b31c0317b0f37"> +9/-2</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/api/project.json<br><br>

**The linting executor was changed to `@nx/linter:eslint` and <br>the lint file patterns were updated to include `.ts`, <br>`package.json`, and `project.json` files in the `api` app.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/50/files#diff-9db28263bde8ec1d5c6460c58fd25ef9a70c6de10f832adde6d2627b2303e466"> +9/-2</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/cli/project.json<br><br>

**The linting executor was changed to `@nx/linter:eslint` and <br>the lint file patterns were updated to include `.ts`, <br>`package.json`, and `project.json` files in the `cli` app.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/50/files#diff-9f0de34787de50028fd144b631da317245a723102be3be906ef859695b126bfd"> +9/-2</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/project.json<br><br>

**The linting executor was changed to `@nx/linter:eslint` and <br>the lint file patterns were updated to include `.ts`, <br>`package.json`, and `project.json` files in the `web` app.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/50/files#diff-ea89cac46be96e04109bb703154c746fbb6e158c73880bb303974216eaae1fe4"> +9/-2</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>project.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        packages/sdk-node/project.json<br><br>

**The linting executor was changed to `@nx/linter:eslint` and <br>the lint file patterns were updated to include `.ts`, <br>`package.json`, and `project.json` files in the `sdk-node` <br>package.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/50/files#diff-f66e3311fc93377ef34b9bfe682dec8ca4abbfb0b575873fbee66f85f0661ae8"> +9/-2</a></td>

</tr>                    
</table></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `describe` tool scans the PR code changes, and generates a description for the PR - title, type, summary, walkthrough and labels. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on a PR.

When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L46) related to the describe tool (`pr_description` section), use the following template:
```
/describe --pr_description.some_config1=... --pr_description.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_description]
some_config1=...
some_config2=...
```

<table><tr><td><details> <summary><strong> Enabling\disabling automation </strong></summary><hr>

- When you first install the app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the describe tool is:
```
pr_commands = ["/describe --pr_description.add_original_user_description=true" 
                         "--pr_description.keep_original_user_title=true", ...]
```
meaning the `describe` tool will run automatically on every PR, will keep the original title, and will add the original user description above the generated description. 

- Markers are an alternative way to control the generated description, to give maximal control to the user. If you set:
```
pr_commands = ["/describe --pr_description.use_description_markers=true", ...]
```
the tool will replace every marker of the form `pr_agent:marker_name` in the PR description with the relevant content, where `marker_name` is one of the following:
  - `type`: the PR type.
  - `summary`: the PR summary.
  - `walkthrough`: the PR walkthrough.

Note that when markers are enabled, if the original PR description does not contain any markers, the tool will not alter the description at all.
        

</details></td></tr>

<tr><td><details> <summary><strong> Custom labels </strong></summary><hr>

The default labels of the `describe` tool are quite generic: [`Bug fix`, `Tests`, `Enhancement`, `Documentation`, `Other`].

If you specify [custom labels](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md#handle-custom-labels-from-the-repos-labels-page-gem) in the repo's labels page or via configuration file, you can get tailored labels for your use cases.
Examples for custom labels:
- `Main topic:performance` - pr_agent:The main topic of this PR is performance
- `New endpoint` - pr_agent:A new endpoint was added in this PR
- `SQL query` - pr_agent:A new SQL query was added in this PR
- `Dockerfile changes` - pr_agent:The PR contains changes in the Dockerfile
- ...

The list above is eclectic, and aims to give an idea of different possibilities. Define custom labels that are relevant for your repo and use cases.
Note that Labels are not mutually exclusive, so you can add multiple label categories.
Make sure to provide proper title, and a detailed and well-phrased description for each label, so the tool will know when to suggest it.        

</details></td></tr>

<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 

</details></td></tr>

</table>

See the [describe usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md) page for a comprehensive guide on using this tool.

</details>

### CODE REVIEW

**Comment by HarshPatel5940** [comment]
thank you for fixing PR title!

**Comment by HarshPatel5940** [comment]
image
This is a known issue and i suggest that this is addressed in a new PR 😄

**Review by rajdip-b — CHANGES_REQUESTED** [review]
@HarshPatel5940 There is a `package.json` under `apps/cli` that is causing the pipeline to fail. Can you remove that and try your tests once?

**Comment by rajdip-b** [comment]
> This is a known issue and i suggest that this is addressed in a new PR 😄

I believe that nx is meant to be used with only one package.json staying at the root level. Introducing multiple versions of them is essentially antipattern. 

Why was it added in the first place?

**Comment by HarshPatel5940** [comment]
> > This is a known issue and i suggest that this is addressed in a new PR 😄
> 
> I believe that nx is meant to be used with only one package.json staying at the root level. Introducing multiple versions of them is essentially antipattern.
> 
> Why was it added in the first place?

It was added by this commit https://github.com/keyshade-xyz/keyshade/commit/9d5c5214b63a44d80875448a3e792b461665412f from you only

**Comment by HarshPatel5940** [comment]
> @HarshPatel5940 There is a `package.json` under `apps/cli` that is causing the pipeline to fail. Can you remove that and try your tests once?

Removed it 👍

**Comment by rajdip-b** [comment]
> It was added by this commit [9d5c521](https://github.com/keyshade-xyz/keyshade/commit/9d5c5214b63a44d80875448a3e792b461665412f) from you only

Thats rather strange :/ No idea why I added this! Anyway, thanks for pointing out!

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
