### PR TITLE
docs: Fix typo in running-the-api.md

### PR DESCRIPTION
**Pull request by rajanmoliya**
## Description

FIX typo in running-the-api.md

Fixes #[ISSUENO]

## Dependencies

NIL

## Future Improvements

NIL

## Mentions

NIL

## Screenshots of relevant screens

keyshade

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Comment by rajdip-b** [comment]
Hey @rajanmoliya! What you pointed out in here is valid, but it is deprecated and no longer in use. Docker now natively supports the `compose` plugin, so you no longer need to install `docker-compose` manually!

**Comment by rajanmoliya** [comment]
okay, maybe I'm using a way older version.

**Comment by rajdip-b** [comment]
Haha! You can check this: https://docs.docker.com/compose/install/

**Comment by rajanmoliya** [comment]
Thanks!

**Pull request closed without merging**
