### PR TITLE
feat(API):  Added icon and removed description field from workspace

### LINKED ISSUE #229: API: Add emoji icon and total projects in a workspace
## Description
We need to have emoji as an icon for workspace and total number of project a workspace have for aesthetic purpose of the ui. 
Also, remove the `description` field.

## Screenshot

image

### PR DESCRIPTION
**Pull request by unamdev0**
## Description

 Added icon and removed description field from workspace

Fixes #229 

## Screenshots of relevant screens
Screenshot 2024-09-15 at 7 37 27 PM

Screenshot 2024-09-15 at 7 39 34 PM

## Additional changes Required

- [] Postman updation

Sample response for fetching all workspace of a user
``` {
            "id": "006bd5bf-43ac-41ad-b7a9-b1317d08f8ee",
            "name": "My first workspace 2",
            "slug": "my-first-workspace-2-0",
            "isFreeTier": true,
            "createdAt": "2024-09-15T13:32:58.131Z",
            "updatedAt": "2024-09-15T13:32:58.131Z",
            "ownerId": "cm0v65bm00000130sigtvry7y",
            "isDefault": false,
            "icon": "🤓",
            "lastUpdatedById": null
        },
 ```
 
 Request Body for creating a new Workspace 
 ```{
    "name": "My first workspace 2",
    "icon":"🤓"
}
```

___

### **PR Type**
enhancement, tests

___

### **Description**
- Replaced the `description` field with an `icon` field in the workspace model, affecting creation and update operations.
- Updated database schema and migration scripts to reflect the removal of `description` and addition of `icon`.
- Modified all relevant tests to accommodate the change from `description` to `icon`.
- Adjusted DTOs and service logic to handle the new `icon` field.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>workspace.ts</strong><dd><code>Replace description with icon in workspace creation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/common/workspace.ts

- Replaced `description` field with `icon` in workspace creation.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-e1de4e05ccfed469f0914045b02f50393adc5d62e90c88db403a562ae99c2075">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>create.workspace.ts</strong><dd><code>Update DTO to include icon instead of description</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/workspace/dto/create.workspace/create.workspace.ts

- Changed optional field from `description` to `icon` in DTO.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-c760c1ab4fbc21b71e76046a55e199b8bff73f6924dcab6615a505afc644f924">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>workspace.service.ts</strong><dd><code>Update workspace service to use icon instead of description</code></dd></summary>
<hr>

apps/api/src/workspace/service/workspace.service.ts

<li>Replaced <code>description</code> with <code>icon</code> in workspace service logic.<br> <li> Removed search functionality for <code>description</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-a92613f23cf2834d52eaedb87c4e8c460d48b6fca8df4ccc968b2a8af19a9c3f">+8/-23</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>migration.sql</strong><dd><code>Database migration to replace description with icon</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/prisma/migrations/20240915122629_add_icon_remove_description_from_workspace/migration.sql

<li>Dropped <code>description</code> column and added <code>icon</code> column in <code>Workspace</code> table.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-2a594d7e7d2a2a9d670d1ee5d06d97d76f08f8862f8781955a08fc883aff020e">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>schema.prisma</strong><dd><code>Update Prisma schema for workspace icon</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/prisma/schema.prisma

<li>Removed <code>description</code> field and added <code>icon</code> field in <code>Workspace</code> model.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-24191263d57c55d02e0cdf394de15225b628d1da20bd826b1541b59b6b02adb4">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>event.e2e.spec.ts</strong><dd><code>Update tests to reflect workspace icon change</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/event/event.e2e.spec.ts

<li>Updated tests to use <code>icon</code> instead of <code>description</code> for workspace.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-e3b2a34abdd21ac689f251a13fc249d534413e3c14ed8a6ae7374021b1663fe2">+12/-12</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>workspace-membership.e2e.spec.ts</strong><dd><code>Modify tests for workspace icon update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts

<li>Modified tests to use <code>icon</code> instead of <code>description</code> for workspace.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-3d2af810cbc31b6ae710d387ba6e8d72d9aaf5e8021ce6266fe5b438c6115c1a">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>workspace.e2e.spec.ts</strong><dd><code>Update workspace tests for icon field</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/workspace/workspace.e2e.spec.ts

- Updated workspace tests to use `icon` instead of `description`.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/435/files#diff-7a691e843fbdae323f1cabe7a12508154fbc917a1a738e5a67a1747fb7c581ea">+12/-12</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by rajdip-b** [comment]
Hey bro, I think you misunderstood the issue. We didn't want to remove the description field. We just wanted to have an additional `icon` field.

**Comment by unamdev0** [comment]
oh, it was mentioned by @kriptonian1  in issue's description, @kriptonian1  can you confirm if you meant to remove it from the frontend

**Comment by rajdip-b** [comment]
Oh right, yes, my bad.

**Review by rajdip-b — CHANGES_REQUESTED** [review]
You would need to update the types and tests in the `api-client` package. You would need to update these files:
- `workspace.types.ts`
- `workspace.spec.ts`

Do let me know if you run into some issue.

**Review by rajdip-b — APPROVED** [review]
LGTM

**Pull request merged**
