### PR TITLE
feat(api): Skip workspace creation if the user is an admin user

### LINKED ISSUE #191: API: Skip workspace creation if the user is an admin user
## Description
Any user that gets created, gets a default workspace associated with them. We don't want admin accounts to get a default workspace. 

## Solution

- Add a `if` check in the [create-user.ts](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/common/create-user.ts) file to skip creation of a workspace if the user is an admin user.
- Add relevant tests to `user.e2e.spec.ts` to check this case.

### PR DESCRIPTION
**Pull request by rajanmoliya**
## Description

Added a check to skip creating a default workspace for admin users in the `createUser` function.

Fixes #191 

## Dependencies

None

## Future Improvements

None

## Mentions

None

## Screenshots of relevant screens

None

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] My changes are not breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

## **Type**
enhancement

___

## **Description**
- Added a check in `createUser` function to skip the creation of a default workspace if the user has `isAdmin` set to true.
- Included a log statement to confirm the creation of an admin user.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>create-user.ts</strong><dd><code>Skip Default Workspace Creation for Admin Users</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/common/create-user.ts
<li>Added a conditional check to skip default workspace creation for admin <br>users.<br> <li> Enhanced logging to include a specific message when an admin user is <br>created.<br>

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/194/files#diff-f84f08523889c22752f3408e2931882ce2e71aff7668ab05448058aab961d310">+7/-7</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Can you add relevant tests in `user.e2e.spec.ts`?

**Comment by rajdip-b** [comment]
Hey @rajanmoliya can you please add the required tests aswell?

**Comment by rajdip-b** [comment]
hey bro @rajanmoliya you still on it?

**Comment by rajanmoliya** [comment]
> hey bro @rajanmoliya you still on it?

No bro.

**Comment by rajdip-b** [comment]
> > hey bro @rajanmoliya you still on it?
> 
> No bro.

Ah, we are just waiting on the test cases. Rest of the PR looks awesome!

**Comment by rajdip-b** [comment]
Cool!

**Comment by rajanmoliya** [comment]
Hey, I'm not able to perform tests due to version mismatching.
I have to close this PR.

**Comment by rajdip-b** [comment]
> Hey, I'm not able to perform tests due to version mismatching. I have to close this PR.

Can you show me what error you are facing? I might be able to help you out!

**Comment by rajanmoliya** [comment]
Screenshot 2024-05-07 172650

**Comment by rajdip-b** [comment]
> Screenshot 2024-05-07 172650

Are you sure you followed the docs about how to set up the project? If not, you can visit [here](hppts://docs.keyshade.xyz)

**Comment by rajanmoliya** [comment]
Yes, I'm sure I followed the docs. (In fact, retried couple of times)
error occurs when I start the server in development mode.

**Comment by rajdip-b** [comment]
It seems that this issue is related to windows. Can you check this thread? https://github.com/getsentry/profiling-node/issues/171

**Comment by rajdip-b** [comment]
Hey @rajanmoliya would you be fixing the PR anytime soon if possible?

**Comment by rajanmoliya** [comment]
@rajdip-b no sorry.

**Comment by rajdip-b** [comment]
Okay!

**Pull request closed without merging**
