### PR TITLE
feat: Integrate pg-boss for job scheduling

### LINKED ISSUE #138: Integrate `pg-boss` for job scheduling
## Description
To run jobs in the background as cronjobs jobs, or jobs that might take up significant resources, we would like to use `pg-boss`. This would allow us to harness the power of our database.

This issue focuses on creating the client API for `pg-boss`

Use this article for reference: https://www.npmjs.com/package/pg-boss

## Solution
- Create a separate module and name it `job-handler`. Add a class called `JobHandler` in `job.handler.ts`.
- It should have a constructor that will initialize pg boss.
- It should have a generic function that will do the actual job on our behalf. The signature would be:
  ```typescript
  async <T, V>registerJob(queue: string, callback: (job: V) => T) => T;
  ```
- Export this module globally (take reference from how the `prisma` module is exported globally).

### PR DESCRIPTION
**Pull request by Allan2000-Git**
## Description

This PR adds a integrates `pg-boss` for job scheduling. This allows us to run jobs in the background as cron jobs or jobs that might take up significant resources.

Fixes #138 

## Dependencies

Installed packages: `pg-boss`

## Future Improvements

N/A

## Mentions

@rajdip-b 

## Screenshots of relevant screens

N/A

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Enhancement

___

### **Description**
- Integrated `pg-boss` for job scheduling by adding a new `JobHandler` class.
- Updated `CommonModule` to include `JobHandler` in providers and exports.
- Added `pg-boss` to the project dependencies in `package.json`.
- Updated `pnpm-lock.yaml` to reflect the new dependencies.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>common.module.ts</strong><dd><code>Add JobHandler to CommonModule providers and exports</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/common/common.module.ts

- Added `JobHandler` to the providers and exports arrays.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/478/files#diff-23dacdf6fbb864b1b7c5c2a009c424ce10e9655b01f877fb307c2e9ba3127de7">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>job.handler.ts</strong><dd><code>Implement JobHandler class for job scheduling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/common/job.handler.ts

<li>Created <code>JobHandler</code> class for managing jobs with <code>pg-boss</code>.<br> <li> Implemented methods to initialize, register, schedule, and stop jobs.<br> <li> Added error handling and logging for job operations.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/478/files#diff-8f9effe10404a8bcf757142dc696df7384597d3baafb2e8a97ec5a85d38af09b">+68/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>package.json</strong><dd><code>Add pg-boss dependency for job scheduling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/package.json

<li>Added <code>pg-boss</code> as a new dependency.<br> <li> Adjusted the order of <code>reflect-metadata</code> in devDependencies.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/478/files#diff-2c40985d6d91eed8ae85ec1c8e754a85984ee32e156a600d2b7a467423d7e338">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pnpm-lock.yaml</strong><dd><code>Update pnpm-lock.yaml with pg-boss dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pnpm-lock.yaml

- Updated lock file to include `pg-boss` and its dependencies.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/478/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb">+269/-10</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by Allan2000-Git** [comment]
@rajdip-b Argument of type V is failing, since it's unknown what type of data is being passed.

**Comment by Allan2000-Git** [comment]
@rajdip-b [https://timgit.github.io/pg-boss/#/./api/constructor?id=newconnectionstring](https://timgit.github.io/pg-boss/#/./api/constructor?id=newconnectionstring) should be a valid constructor

**Review by rajdip-b — CHANGES_REQUESTED** [review]

**Comment by Allan2000-Git** [comment]
@rajdip-b A bit help here on why tests are failing. I followed `pg-boss` documentation and it's says to create an instance using `PgBoss` class itself.

**Comment by rajdip-b** [comment]
> @rajdip-b A bit help here on why tests are failing. I followed `pg-boss` documentation and it's says to create an instance using `PgBoss` class itself.

Yes, you would need that. What im saying is, you can have that instance of the class in a nestjs provider. you can check how redis is implemented in a similar manner. and you can also look at how the tests work for that.

**Comment by rajdip-b** [comment]
Hey dude, i'm closing this PR since this seems really obsolete as of now. I'll also be closing the issue. Thanks for grinding the time in here!

**Pull request closed without merging**
