### PR TITLE
feat(api): Replace `projectId` with `name` and `slug` in workspace-role response. 

### LINKED ISSUE #429: API: Replace `projectId` with `name` and `slug` in `workspace-role` response.
## Description

Workspace roles have one or more projects associated with it. When we try to fetch a role / create one or update one, we want to also fetch some details regarding the project.

For now, we would like to get a list of `name` and `slug` for all the associated projects.

## Solution
- Create role: https://github.com/keyshade-xyz/keyshade/blob/2f4edecd0837f7658892a37902c62f05ab96c884/apps/api/src/workspace-role/service/workspace-role.service.ts#L97-L103
- Update role: https://github.com/keyshade-xyz/keyshade/blob/2f4edecd0837f7658892a37902c62f05ab96c884/apps/api/src/workspace-role/service/workspace-role.service.ts#L228-L234
- Get role: https://github.com/keyshade-xyz/keyshade/blob/2f4edecd0837f7658892a37902c62f05ab96c884/apps/api/src/workspace-role/service/workspace-role.service.ts#L445-L447
- Update the tests in `workspace-role.e2e.spec.ts` to reflect these scenarios.

### PR DESCRIPTION
**Pull request by Nil2000**
## Description

Resolved according to the requirement and also added fixed test file as well<br />

Fixes #429

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Enhanced the workspace-role service to include `slug` and `name` fields in the project data response.
- Updated end-to-end tests to verify the presence of `slug` and `name` fields in the project data.
- These changes ensure that the API response now provides more detailed project information, improving data accessibility.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>workspace-role.service.ts</strong><dd><code>Enhance project data retrieval in workspace-role service</code>&nbsp; </dd></summary>
<hr>

apps/api/src/workspace-role/service/workspace-role.service.ts

<li>Added <code>slug</code> and <code>name</code> fields to project selection in workspace-role <br>service.<br> <li> Updated include statements to fetch additional project details.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/432/files#diff-fa0a0e5d18d758148d81c6236ae88c9e4e117214826e1a03cc9cc0441d111320">+25/-3</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>workspace-role.e2e.spec.ts</strong><dd><code>Update workspace-role tests for additional project fields</code></dd></summary>
<hr>

apps/api/src/workspace-role/workspace-role.e2e.spec.ts

<li>Updated tests to check for <code>slug</code> and <code>name</code> fields in project data.<br> <li> Ensured test cases reflect changes in workspace-role response <br>structure.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/432/files#diff-8cb77aad66a47879970bb3d9086df36f7477e273caf90a319c589e7a221cd30b">+12/-4</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by rajdip-b** [comment]
@Nil2000 could you please self assign the issue?

**Review by rajdip-b — CHANGES_REQUESTED** [review]
For all the `select` blocks, unselect the `projectId` field and instead, select `project.select.id`. That way, things look more organized.

**Comment by rajdip-b** [comment]
@Nil2000 the pr looks good. Would you be open to making the changes to `api-client` package in this PR? Since the changes are directly related.

**Review by rajdip-b — APPROVED** [review]

**Comment by Nil2000** [comment]
Yeah sure, but I am not sure where I need to make the change.
May be in the following file
1. In `workspace-role.types.d.ts` interface `WorkspaceRole`

Is that it? Or are there more changes left? 🤔

**Comment by rajdip-b** [comment]
- https://github.com/keyshade-xyz/keyshade/blob/e167f537bca0218eb071b42e31d963e9852e2885/packages/api-client/src/types/workspace-role.types.d.ts#L14-L16
- https://github.com/keyshade-xyz/keyshade/blob/develop/packages/api-client/tests/workspace-role.spec.ts

These are the places. You can run the tests using `pnpm test:api-client`

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
