### PR TITLE
feat(api): Reading `port` Dynamically

### LINKED ISSUE #134: Read `port` dynamically in `api`
## Description
image

We would like to give users the option to update the port from the environment without needing to alter any code. This will involve changing the `main.ts` and `Dockerfile` files.

## Solution
- [ ] Create an environmental variable named `API_PORT`
- [ ] Add it to `.env.example`
- [ ] In the `main.ts` file, read this environmental variable. If it's not set, default the `port` to `4200`
- [ ] In the `Dockerfile`, update the `EXPOSE 4200` to `EXPOSE ${API_PORT:-4200}`

## Additional context
All the related files are stored under `apps/api`

### PR DESCRIPTION
**Pull request by Animesh7853**
## Description
 Made the port dynamic in the api as instructed in the issue

Fixes #134 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions
@rajdip-b 

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

## **Type**
enhancement

___

## **Description**
- Dynamically set the API port in the main application file using the `API_PORT` environment variable, with a fallback to 4200 if not set.
- Added an example for the `API_PORT` environment variable in the `.env.example` file.
- Modified the Dockerfile to expose the port defined by the `API_PORT` environment variable, with a fallback to 4200.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>main.ts</strong><dd><code>Dynamically Set API Port from Environment Variable</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/main.ts
<li>Dynamically set the API port using environment variable <code>API_PORT</code>, with <br>a fallback to 4200 if not set.<br>

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/170/files#diff-32c5294dd7ca131397ef57a87c3e0cf38ea5c2e4ca0061c602e73f7f00514c1a">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>.env.example</strong><dd><code>Added API_PORT Environment Variable Example</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.env.example
- Added `API_PORT` environment variable example.

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/170/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8c">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Use API_PORT Environment Variable in Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/Dockerfile
<li>Modified <code>EXPOSE</code> to use <code>API_PORT</code> environment variable with a fallback <br>to 4200.<br>

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/170/files#diff-9ada278a9adf2846ef744063b304ed43826d904a8e1729669a1035ee26e036c6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Would you please update the docs for [this](https://docs.keyshade.xyz/contributing-to-keyshade/environment-variables) page? You can find the relevant docs in the `docs` folder!

**Comment by Animesh7853** [comment]
> Would you please update the docs for [this](https://docs.keyshade.xyz/contributing-to-keyshade/environment-variables) page? You can find the relevant docs in the `docs` folder!

Okay I'll do

**Review by rajdip-b — APPROVED** [review]

**Comment by rajdip-b** [comment]
LGTM! @Animesh7853

**Pull request merged**
