### PR TITLE
feat: Add email template for sending OTP to the user

### LINKED ISSUE #51: Create a mail template for OTP
## Description

The current OTP mail looks boring TBH. Make a more vibrant OTP mail.
image

## Tasks
- [x] Create the template in Figma
- [ ] Export the code and set it in the present mail code

### PR DESCRIPTION
**Pull request by Allan2000-Git**
## Description
This PR adds an email template for sending OTP to the user.

Fixes #51 

## Dependencies
No new dependencies introduced.

## Future Improvements
N/A

## Mentions
@rajdip-b 

## Screenshots of relevant screens
otp-email-template

## Developer's checklist
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**
- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update
- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Enhancement

___

### **Description**
- Introduced a new React component `OTPEmailTemplate` for sending OTP emails with a vibrant design.
- Updated styles in `common-styles.ts` to support the new OTP email template.
- Integrated the new OTP email template into the mail service, replacing the old HTML string with a component-based approach.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>otp-email-template.tsx</strong><dd><code>Add OTP Email Template Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/mail/emails/otp-email-template.tsx

<li>Added a new React component for OTP email template.<br> <li> Utilized <code>BaseEmailTemplate</code> for consistent styling.<br> <li> Included OTP display and expiration message.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/582/files#diff-cb1dab75b994f75f9b83acd441024c61b2e403459978a81218be6227cb7df2b6">+34/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>common-styles.ts</strong><dd><code>Update Styles for OTP Email Template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/mail/emails/styles/common-styles.ts

<li>Added <code>otpStyle</code> for styling OTP text.<br> <li> Modified <code>workspaceDetails</code> style for better appearance.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/582/files#diff-6c18bdd927da4fa501b0e5213940d56c0920bbc9d88b136a29269a688e147555">+10/-2</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>mail.service.ts</strong><dd><code>Integrate OTP Email Template in Mail Service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/mail/services/mail.service.ts

<li>Integrated new OTP email template in mail service.<br> <li> Replaced old HTML string with React component rendering.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/582/files#diff-7eef5c389ba70573686bfbc12ad026cd9a596980cb56c7192d0958d156d5e39a">+9/-19</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by rajdip-b — COMMENTED** [review]
Can you drop a preview of how this looks?

**Comment by Allan2000-Git** [comment]
> Can you drop a preview of how this looks?

Have already attached in the PR description
otp-email-template

**Comment by Allan2000-Git** [comment]
@rajdip-b Can you review the changes made?

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
