### PR TITLE
feat(api): add logout endpoint to clear token cookie

### LINKED ISSUE #223: API: Add logout endpoint
## Description

Add an endpoint to log out. The functionality will be very simple - just clear the `token` cookie.

## Solution

- Add a controller in auth controller.
- Do not add `@Public` to it.
- Create a service function that will unset the `token` cookie.

### PR DESCRIPTION
**Pull request by ShreyamKundu**
## Description

Added a logout endpoint to the  auth.controller.ts file and the logout function in the auth.service.ts file. This endpoint clears the token cookie, ensuring the user is logged out securely.

Fixes #223 

## Dependencies

NA

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b 

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
Enhancement

___

### **Description**
- Added a new `logout` endpoint in the `auth.controller.ts` file to handle user logout by clearing the `token` cookie.
- Implemented a `logout` method in the `auth.service.ts` file that clears the `token` cookie and logs the action.
- Ensured the logout process sends a success message upon completion.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>auth.controller.ts</strong><dd><code>Add logout endpoint to AuthController</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/auth/controller/auth.controller.ts

<li>Added a new POST endpoint <code>logout</code> to the AuthController.<br> <li> The endpoint calls the <code>logout</code> method from the AuthService.<br> <li> Sends a success message upon logout.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/581/files#diff-ca5c58065b10468a07314a5a9224336ac37df84a4a0e769babb2ed040cf8c82a">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>auth.service.ts</strong><dd><code>Implement logout functionality in AuthService</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/api/src/auth/service/auth.service.ts

<li>Introduced a <code>logout</code> method in AuthService.<br> <li> Clears the <code>token</code> cookie from the response.<br> <li> Logs the logout action.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/581/files#diff-b133cdd3d1772bc73698061218512fd024ce1ed7cd9eaeb27858e6acb444b90b">+12/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by rajdip-b — APPROVED** [review]
LGTM

**Comment by rajdip-b** [comment]
Can you also add the request under "Auth Controller" in Bruno?

**Comment by ShreyamKundu** [comment]
okay...i will try that

**Comment by ShreyamKundu** [comment]
@rajdip-b I have added the request in auth controller in Bruno

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
