### PR TITLE
chore: Email validation

### LINKED ISSUE #463: WEB: suggesting changes while adding waitlist
# Description 
- [x] [chore] Right now after adding the user to the waitlist there the text field remains the same, instead lets clear the text field. (#481)
- [x] [chore] Perform some validation on the email field as `ff@ff` and other things is allowed which should not be allowed. (#487)
- [x] [chore] Only show toast when the whitelist response is successful. (#490)
- [ ] [feat] Check if user has already whitelisted. (#492)

---
Target file: https://github.com/keyshade-xyz/keyshade/blob/72281e66569b05011a7b79a94ae502eaac0b3a6d/apps/web/src/components/hero/index.tsx

### PR DESCRIPTION
**Pull request by bansal-harsh-2504**
## Description

Implemented email validation using zod.

Fixes #463 

## Mentions

@rajdip-b 

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] There are no UI/UX issues

### CODE REVIEW

**Comment by bansal-harsh-2504** [comment]
@rajdip-b Can you please attach hacktoberfest label before merging?

**Comment by bansal-harsh-2504** [comment]
@rajdip-b Can you please attach hacktoberfest label before merging?

**Comment by rajdip-b** [comment]
@kriptonian1 can you review this?

**Review by kriptonian1 — APPROVED** [review]
LGTM 🚀

**Comment by kriptonian1** [comment]
@bansal-harsh-2504 Can you pls fix the merge conflit in the `pnpm-lock.yaml` file. The easy way to fix this issue is to delete the `pnpm-lock.yaml` file, and then do `pnpm i`

**Comment by bansal-harsh-2504** [comment]
@kriptonian1 Sorry, I don't know what I did to close this pr but I will create another one for this.

I think I need to learn git in depth first

Apologies once again

**Comment by bansal-harsh-2504** [comment]
@kriptonian1  #487

**Pull request closed without merging**
