### PR TITLE
feat: authentication with Google and GitHub 

### LINKED ISSUE #3: [USER] Log in using GitHub
Users should be able to log in to our platform using GitHub. When doing so, we should scrape off the following things and persist them in our db: 
- avatar
- name
- email

### PR DESCRIPTION
**Pull request by Abbhiishek**
## Type
enhancement

___

## Description
This PR introduces several enhancements to the application:
- Implemented user authentication and registration using Clerk.
- Added a webhook handler to manage user creation and updates.
- Integrated the ClerkProvider component into the main application layout to manage user authentication state.
- Introduced a Prisma client for structured data management.
- Added new environment variables for Clerk and webhook authentication.
- Updated the TypeScript configuration with new paths.
- Updated the documentation to reflect the new environment variables.
- Added new dependencies for Clerk, themes, and svix.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>page.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/(auth)/login/[[...sign-in]]/page.tsx<br><br>

**Added a new SignIn component from Clerk to handle user <br>authentication.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-37c22ba33e5130d6fac2b32f5733bd1ca1015af1a1969f0c17c439411f723a37"> +9/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>page.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/(auth)/signup/[[...sign-up]]/page.tsx<br><br>

**Added a new SignUp component from Clerk to handle user <br>registration.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-631846002799f87ee829607166f39ff89594df4f4814fc4093e0ee02d0fa0a9a"> +9/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Providers.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/Providers.tsx<br><br>

**Introduced a new ClerkProvider component to manage user <br>authentication state.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-9fa9af05865e67d34f1cb7329c4875f7db82b34261d6ccbf47e7f361caa374e1"> +16/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>route.ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/api/webhook/user/route.ts<br><br>

**Implemented a new webhook handler to manage user creation <br>and updates.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-24de47898e9391b38a760e2f4bf1805bd40731307b90480119979b444e339617"> +78/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>layout.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/layout.tsx<br><br>

**Integrated the Providers component into the main application <br>layout.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-c235c52626fe2cfbb53241bb015bdd7b5f5a28f9a10a08e1f401238e773fa7ad"> +6/-1</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>prismadb.ts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/lib/prismadb.ts<br><br>

**Added Prisma client for database operations.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-732fa0d371384eec389ec2440bc09e1c8e21caebcaaf3a079563b6cd0ee4aff1"> +5/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>schema.prisma&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/prisma/schema.prisma<br><br>

**Introduced a new Prisma schema for structured data <br>management.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-533d39bfbd045338d31d0acd79fe0b6163f1e26fccb6441a7f4e9dac6e3ddd61"> +71/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>.env.example&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        .env.example<br><br>

**Added new environment variables for Clerk and webhook <br>authentication.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8c"> +6/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>tsconfig.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/tsconfig.json<br><br>

**Added new paths configuration for TypeScript.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-5ccca1924ddc8226881065b3da52870b4aa307c32dbacfc19eb22b8d5c8713f3"> +3/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>environment-variables.md&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        docs/contributing-to-keyshade/environment-variables.md<br><br>

**Updated the documentation to include new environment <br>variables.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-2bf98f3c57ba5baaa3603870cea1ee6984fea12550638d22e65bfe23f3234af1"> +4/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>package.json&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        package.json<br><br>

**Added new dependencies for Clerk, themes, and svix.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/49/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519"> +3/-0</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

## Description

This PR introduces several new features and updates to enhance our application's authentication and data management capabilities.

### Features
**Authentication Support for Google and GitHub**: Users can now authenticate using their Google or GitHub accounts. This provides a seamless and secure way for users to access our application.

**Webhook for User Account Updates**: A new webhook has been implemented that triggers whenever a user creates or updates their account. This allows us to keep our user data up-to-date and consistent across our application.

**Prisma Schema Addition to Web App Module**: The Prisma schema has been added to the web app module. This will facilitate efficient and structured data management in our application.

Fixes #3 #4 

## ENV Updates

New Environment Variables: Three new secrets have been introduced - **CLERK_SECRET_KEY**, **NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY**, and **CLERK_WEBHOOK_SIGNING_KEY**. These will be used for secure communication and data transfer.

## Dependencies

1. `svix`: For managing and handling webhooks (verify webhook payload)
2. `@clerk/nextjs`: For integrating Clerk authentication in Next.js applications.
3. `@clerk/themes`: For theming support in Clerk.

## Future Improvements

- Login and Signup screen to be designed.

## Mentions

@rajdip-b

### Login Page
image

### Sign Up page
image

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [x] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Hey man, thats some great work. Although, I would like to flag off some stuff. See, the user management and stuff like those are already built into the backend under `apps/api`. Naturally, we would like all of these computations to happen in the backend. This is so because in the longer run, we might want to give the users the opportunity to lon in via the cli

**Comment by Abbhiishek** [comment]
sure i will try to migrate it to apps/api . However i never code with nestjs . need sometime to figure out stuffs

**Comment by rajdip-b** [comment]
> sure i will try to migrate it to apps/api . However i never code with nestjs . need sometime to figure out stuffs

We are always there for assisting. Also, most of the code regarding authentication and issuing JWTs are already done. All you need to do is integrate github and google and we are good to go

**Comment by Abbhiishek** [comment]
> > sure i will try to migrate it to apps/api . However i never code with nestjs . need sometime to figure out stuffs
> 
> We are always there for assisting. Also, most of the code regarding authentication and issuing JWTs are already done. All you need to do is integrate github and google and we are good to go

Clerk issues Jwt token of their own , we can tweak body of it to some extend.

**Comment by rajdip-b** [comment]
@Abbhiishek that's not gonna work then :/ We need to move to manual authentication. I am linking some articles for your reference. 
- https://www.loginradius.com/blog/engineering/oauth-implemenation-using-node/
- https://medium.com/@jackrobertscott/easy-google-auth-with-node-js-99ac40b97f4c
- https://www.loginradius.com/blog/engineering/google-authentication-with-nodejs-and-passportjs/
- https://medium.com/@jackrobertscott/easy-github-auth-with-node-js-502d3d8f8e62

**Comment by Abbhiishek** [comment]
@rajdip-b i am not getting the point why clerk is a bad choice here. Open to feedback

- clerk provide web hooks i am able to save all user data to our own database
- it has node-sdk that can work in nestjs backend https://clerk.com/docs/references/nodejs/overview

**Comment by rajdip-b** [comment]
Hmm, okie. Well see the bottomline is this:
- Get the users to authenticate using Github and Google
- Upon valid signup, we need to fetch their details - name, email, profile picture
- We need to store it in our db and then, we start with our own flow.
- As for the JWT, if the jwt signing secret can be modified, that would be really nice since we wouldn't need to generate ours

If these can be done, I am totally fine. I just dont want to overcomplicate the flow thats all

**Comment by HarshPatel5940** [comment]
> @rajdip-b i am not getting the point why clerk is a bad choice here. Open to feedback
> 
> * clerk provide web hooks i am able to save all user data to our own database
> * it has node-sdk that can work in nestjs backend https://clerk.com/docs/references/nodejs/overview

We can do this. There is a one concern, lets say we suddenly get a high rush of users (10k+) and clerk starts charging us. there would be a chance we would not like to pay that as its costly, right?

---

Now if we are planning to Oauth only for **github and google**, i feel it would be better that we handle our authentication manually in **nestJs** itself. Now why this
1) since we are planning to host an api, we could easily host this as well
2)  next reason is because I would definitely prefer complete control on auth data so we can modify and use the data as needed, else where.

**Comment by rajdip-b** [comment]
@Abbhiishek I'm sort of in agreement with @HarshPatel5940 in this matter. I mean, paying extra just to make something that takes 10 20 LOC is not ideal. You might want to give a look at passportjs. Alternatively, you can also collaborate with Harsh to build this feature!

**Comment by rajdip-b** [comment]
@Abbhiishek @HarshPatel5940 hey folks! Made any progress in this one?

**Comment by rajdip-b** [comment]
@Abbhiishek @HarshPatel5940 closing this one since @HarshPatel5940 will be creating a new PR.

**Pull request closed without merging**
