### PR TITLE
Create landing website

### LINKED ISSUE #11: Create landing website
# Description
Create the landing page of the website using Next.js and typescript. The boilerplate code is already present in `apps/web`. 

Website design's [Figma link](https://www.figma.com/file/4Y2qkiU7yoifHu37iX41n8/keyshade-coming-soon?type=design&node-id=0%3A1&mode=dev)

> **Note:** this website must have a lighthouse score of above 90

## metadata structure
```tsx
import { Metadata } from "next";

const description = "Manage all your secrets securely with public key encryption and realtime based tools, that seamlessly fits into your codebase";
const name = "keyshade";

export const metadata: Metadata = {
  metadataBase: new URL("https://keyshade.xyz/"),
  title: {
    default: name,
    template: `%s | ${name}`,
  },
  description: description,
  keywords: [
"Keyshade",
"secrets integration",
"codebase security",
"Public Key Encryption",
"secret rotation",
"auto revoke",
"collaboration",
"data security",
"secrets management",
"secure code secrets",
"realtime secrets integration",
"encryption for secrets",
"automated secret rotation",
"team collaboration secrets",
"secure runtime environment",
"secrets management tool",
"codebase security solution",
"cybersecurity for secrets",
"API security",
"key management",
"secure data transfer",
"secure secrets sharing",
"effortless secrets management",
"Keyshade features",
"cybersecurity solution",
"secure software development",
"automated access revocation",
"secure secrets storage",
"developer tools security",
"API key security",
"codebase encryption",
"team-based secrets management"
  ],
  applicationName: name,
  openGraph: {
    title: name,
    description: description,
    type: "website",
    locale: "en_US",
    images: "https://keyshade.xyz/thumbnail.png",
  },
  twitter: {
    card: "summary_large_image",
    title: name,
    description: description,
    creator: "@keyshade_xyz",
    creatorId: "1738929014016966656",
  },
  robots: {
    index: true,
    follow: true,
    noarchive: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};
```

### PR DESCRIPTION
**Pull request by SRINJAYDASGUPTA-Git**
## Type
bug_fix, enhancement

___

## Description
This PR includes several bug fixes and enhancements to the landing page of the web application. The most significant changes include:
- Creation of new `Killers` and `Links` components to improve code reusability and readability.
- Update of the metadata object in `layout.tsx` with more detailed information about the application.
- Update of the `Index` function in `page.tsx` to use the new components and update the background color and images.

___

## PR changes walkthrough
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Killers.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/components/Killers.tsx<br><br>

**A new component `Killers` was created. This component takes <br>an image and a Twitter username as props and renders a user <br>profile with a link to the Twitter account.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/34/files#diff-054c24770c32b936b66eef848a79cb83c5381b27155c8acbd3d77d49e502ba95"> +30/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Links.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/components/Links.tsx<br><br>

**A new component `Links` was created. This component takes an <br>icon, a description, and a link as props and renders a <br>clickable link with an icon and description.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/34/files#diff-3bced7d093b970a35857f589bad65942380f20545f3a016e2716bfbc31ae9eb8"> +32/-0</a></td>

</tr>                    
</table></details></td></tr><tr><td><strong>Bug_fix</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>layout.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/layout.tsx<br><br>

**The metadata object was updated with more detailed <br>information about the application, including keywords, <br>openGraph data, Twitter data, and robots data.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/34/files#diff-c235c52626fe2cfbb53241bb015bdd7b5f5a28f9a10a08e1f401238e773fa7ad"> +70/-4</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>page.tsx&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></summary>
      <ul>
        apps/web/app/page.tsx<br><br>

**The `Index` function was updated to use the new `Links` and <br>`Killers` components. The background color and images were <br>also updated.**
</ul>
    </details>
  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/34/files#diff-fd023d75d1ed8133295c3359120c1f334b252c95341a0c411018fd0e8411c5e3"> +13/-65</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

## Description

- Fix: fixed the bg contrast
- Fix: fixed the grid size
- fix: fixed the metadata
- Fix: resolved warnings
<br />

Fixes #11 

## Dependencies

<NA>

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

code
image

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Comment by kriptonian1** [comment]
@SRINJAYDASGUPTA-Git as I mentioned in your previous pr, use [`svgr`](https://react-svgr.com/) for the SVGs, don't put them inside the image tag. Making draggable=false won't change the fact that you are using it as an image.

**Review by rajdip-b — APPROVED** [review]
Everything looks real nice to me. @kriptonian1 please give it a look. lemme know

**Comment by rajdip-b** [comment]
> @SRINJAYDASGUPTA-Git as I mentioned in your previous pr, use [`svgr`](https://react-svgr.com/) for the SVGs, don't put them inside the image tag. Making draggable=false won't change the fact that you are using it as an image.

maybe you can drop in some refs as to what he can do to fix this.

**Comment by SRINJAYDASGUPTA-Git** [comment]
> @SRINJAYDASGUPTA-Git as I mentioned in your previous pr, use [`svgr`](https://react-svgr.com/) for the SVGs, don't put them inside the image tag. Making draggable=false won't change the fact that you are using it as an image.

On it 👍🏼

**Comment by rajdip-b** [comment]
Hey man hope you fixed them as @kriptonian1 asked?

**Comment by SRINJAYDASGUPTA-Git** [comment]
> Hey man hope you fixed them as @kriptonian1 asked?

just did
pls check @kriptonian1 @rajdip-b

**Comment by rajdip-b** [comment]
link #11

**Review by rajdip-b — APPROVED** [review]
Hey man this seems cool to me! Im merging this!

**Pull request merged**
