### PR TITLE
fix(web): alignment issue in “Collaboration made easy” section

### LINKED ISSUE #177: Alignment issue in “Collaboration made easy” section
**Describe the bug**
The “Approval before Commit” section should contain within the main grid, but instead it is overflowing. 

**To Reproduce**

**Expected behavior**
The “Approval before Commit” section should contain within the main grid
Example:
image

**Screenshots**
image

**Desktop (please complete the following information):**

 - OS: All
 - Browser All

**Additional context**

### PR DESCRIPTION
**Pull request by PriyobrotoKar**
## Description

Fixed the issue where the “Approval before Commit” section was overflowing from the main grid. <br />

Fixes #177 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

## **Type**
enhancement, bug_fix

___

## **Description**
- Improved the layout and responsiveness of the "Collaboration made easy" section by transitioning to a grid layout and adjusting card components for better alignment.
- Introduced the ability to add custom styling to `Card` components through a new `className` prop, enhancing flexibility and customization.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Improved Layout and Responsiveness in "Collaboration made easy" </code><br><code>Section</code></dd></summary>
<hr>

apps/web/src/components/colabEasy/index.tsx
<li>Changed the layout from <code>flex</code> to <code>grid</code> for better alignment and <br>responsiveness.<br> <li> Adjusted the <code>Card</code> components to span multiple rows or columns as <br>needed.<br> <li> Added <code>className</code> props to <code>Card</code> and <code>FollowerPointerCard</code> components for <br>custom styling.

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/178/files#diff-bb0ee8872c7642b1cf4cfcf2c20485d8989b412e6144542efa7b2ff84d357196">+35/-39</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Added Custom Styling Capability to Card Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/src/components/shared/card/index.tsx
<li>Introduced <code>className</code> prop to allow custom styling.<br> <li> Utilized <code>cn</code> utility function for conditional class name concatenation.

</details>
    

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/178/files#diff-04d5bb19ea2b84b515f1db105c78c36d3e5353d407e338cd37b1fd5bd3a27fcf">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by kriptonian1** [comment]
@PriyobrotoKar can you add a screenshot

**Comment by PriyobrotoKar** [comment]
> @PriyobrotoKar can you add a screenshot

Yes , here's the screenshot

screenshot

**Review by rajdip-b — APPROVED** [review]

**Comment by PriyobrotoKar** [comment]
@kriptonian1 I have found another way to fix this alignment issue by taking care of these **possible issues** mentioned [in this PR Review](https://github.com/keyshade-xyz/keyshade/pull/178#issuecomment-2041601245).

Should I push this new fix or the previous fix was good enough?

### This is how it looks after this new fix:

**Comment by PriyobrotoKar** [comment]
@kriptonian1 I have found another way to fix this alignment issue by taking care of these **possible issues** mentioned [in this PR Review](https://github.com/keyshade-xyz/keyshade/pull/178#issuecomment-2041601245).

Should I push this new fix or the previous fix was good enough?

**This is how it looks after this new fix:**

image

**Comment by rajdip-b** [comment]
@PriyobrotoKar we would be really glad if you can make those fixes!

**Comment by rajdip-b** [comment]
@kriptonian1 can you drop in your reviews?

**Comment by kriptonian1** [comment]
LGTM

**Review by kriptonian1 — APPROVED** [review]
LGTM

**Comment by PriyobrotoKar** [comment]
> @PriyobrotoKar Congrats on your first successful MR at keyshade!!

Thanks!! Infact this is my first ever successful MR in any open source project. Will be trying to contribute more in future.

**Comment by rajdip-b** [comment]
Looking forward to it! 

P.S. you can try a few API issues aswell!

**Pull request merged**
