### PR TITLE
fix(cli): Removed unnecessary console log in secrets

### LINKED ISSUE #302: CLI: Add functionality to operate on Secrets
## Description

We would like to perform the following operations for secrets using our CLI:

- List all secrets under a project (`keyshade secret list <projectSlug>`)
- Fetch all revisions of a secret (`keyshade secret revisions <secretSlug>`)
- Create a secret (`keyshade secret create <projectSlug>(refer postman for parameters)`)
- Update a secret (`keyshade secret update <secretSlug> (refer postman for parameters)`)
- Rollback a secret (`keyshade secret rollback <secretSlug> --environment-slug/-e <> --version/-v <>`)
- Delete a secret (`keyshade secret delete <secretSlug>`)

## Solution

- Create an implementation of `command.interface.ts` and name if `SecretCommand`.
- Stash all the functions in `src/commands/secret`.
- Use the `secretController` under `ControllerInstance` to make the API calls.

### PR DESCRIPTION
**Pull request by anudeeps352**
## Description

Removed an unnecessary console log <br />

Fixes #302 

## Developer's checklist

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-check on my work

**If changes are made in the code:**

- [X] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [X] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [X] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

___

### **PR Type**
enhancement

___

### **Description**
- Removed an unnecessary console log statement from the `ListSecret` command in the CLI application.
- This change enhances the code by cleaning up redundant output, improving readability and performance.

___

PRDescriptionHeader.CHANGES_WALKTHROUGH
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>list.secret.ts</strong><dd><code>Remove unnecessary console log from ListSecret command</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/cli/src/commands/secret/list.secret.ts

<li>Removed an unnecessary console log statement.<br> <li> Improved code readability by eliminating redundant output.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/515/files#diff-2a60ffa339c54c754c130fc45b4cda2ef7dd8cc472e8e18c2c329f8f3031ae7b">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by rajdip-b** [comment]
I think somehow you have comitted all the files again.

**Comment by anudeeps352** [comment]
Yeah I was also thinking the same. I dunno how it happened,I only changed the console log

**Comment by anudeeps352** [comment]
Hey if its easy enough then ig you can directly modify the file itself and just close this pr right ? I dont think such a small issue requires a pr

**Comment by anudeeps352** [comment]
Ig now its fine right ?

**Review by rajdip-b — APPROVED** [review]

**Pull request merged**
