### PR TITLE
chore: Email validation

### LINKED ISSUE #463: WEB: suggesting changes while adding waitlist
# Description 
- [x] [chore] Right now after adding the user to the waitlist there the text field remains the same, instead lets clear the text field. (#481)
- [x] [chore] Perform some validation on the email field as `ff@ff` and other things is allowed which should not be allowed. (#487)
- [x] [chore] Only show toast when the whitelist response is successful. (#490)
- [ ] [feat] Check if user has already whitelisted. (#492)

---
Target file: https://github.com/keyshade-xyz/keyshade/blob/72281e66569b05011a7b79a94ae502eaac0b3a6d/apps/web/src/components/hero/index.tsx

### PR DESCRIPTION
**Pull request by bansal-harsh-2504**
## Description

Implemented email validation using Zod.

Related to #463 

## Mentions

@rajdip-b @kriptonian1

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] There are no UI/UX issues

___

### **PR Type**
enhancement, dependencies

___

### **Description**
- Implemented email validation in the Hero component using the Zod library to ensure valid email addresses are entered.
- Updated the toast message to prompt users to enter a valid email address.
- Added the Zod library to the project's dependencies in `package.json`.
- Updated the `pnpm-lock.yaml` file to reflect the addition of the Zod library and other dependency updates.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Implement email validation in Hero component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/src/components/hero/index.tsx

<li>Added email validation using Zod.<br> <li> Updated toast message for invalid email.<br>

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/487/files#diff-7613ce5c9e898c20a2427ba5bf13810f61bb0a532139896e00a54cd0285ad40c">+7/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>package.json</strong><dd><code>Add Zod library to project dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/package.json

- Added Zod library as a dependency.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/487/files#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>pnpm-lock.yaml</strong><dd><code>Update pnpm lock file with new dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pnpm-lock.yaml

- Updated lock file to include Zod and other dependency changes.

</details>

  </td>
  <td><a href="https://github.com/keyshade-xyz/keyshade/pull/487/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb">+35/-302</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by rajdip-b — APPROVED** [review]
LGTM

**Comment by rajdip-b** [comment]
@kriptonian1 merge this if you feel its good

**Review by kriptonian1 — APPROVED** [review]
LGTM

**Pull request merged**
